src/service/Service.js, src/service/createService.js, src/service/selectWith.js, tests/service/Service.test.js
I created a duplicate PR, because the another i merged in a wrong branch.
#15
=> Improving the Custom Methods and Add Batch on get Method

src/index.js, src/utils/selectorTypes.js
=> add types functions on index

package.json, src/selectorTypes.js, tests/unit/selectorTypes.test.js, yarn.lock
=> Replacing moment to luxon

package.json, src/Resources.js, src/index.js, src/server.js, tests/integration/app.minimal.test.js, tests/integration/minimal/config/database.json, tests/integration/minimal/endpoints/Tasks.js, tests/integration/minimal/models/Tasks.js, tests/integration/minimal/models/index.js, tests/integration/minimal/routes.js, tests/integration/minimal/seeders/20181026170039-create_task.js, tests/integration/minimal/server.js, yarn.lock
=> Feature minimal

package.json, src/selectorTypes.js, tests/unit/selectorTypes.test.js, yarn.lock
Reverts davidcostadev/fastexpress#52
=> Revert "Replacing moment to luxon"

src/Resources.js, tests/integration/app.minimal.test.js, tests/integration/minimal/routes.js
=> Fix when is on root improve the response of tree

.travis.yml
https://travis-ci.community/t/cant-install-mysql-5-7-on-ubuntu-trusty/4311/7
=> Run build on Xenial image

.circleci/config.yml, .travis.yml, tests/integration/config/database.json
=> Fix travis

examples/basic/package.json, examples/basic/yarn.lock, examples/complete/package.json, examples/complete/yarn.lock, package.json, yarn.lock
=> Bumb Versions

README.md
=> Improving readme usage

src/Controller.js, src/Resources.js, src/Service.js, src/endpoint.js, src/routers.js, src/server.js, src/validate.js
=> Add some jsdos

examples/auth/src/models/index.js, examples/basic/src/models/Tasks.js, examples/basic/src/models/index.js, examples/basic/src/seeders/20181026170039-create_task.js, examples/complete/src/models/Tasks.js, examples/complete/src/models/index.js, examples/complete/src/routes.js, examples/complete/src/seeders/20181026170039-create_task.js, examples/complete/src/services/TaskServices.js, jsconfig.json, package.json, rollup.config.js
=> Fix all prettier formats

examples/complete/src/routes.js
=> Fix complete example fastexpress import

examples/auth/src/endpoints/Tasks.js, examples/auth/src/endpoints/Users.js, examples/complete/src/services/TaskServices.js, src/createService.js, src/endpoint.js, tests/integration/minimal/models/index.js, tests/integration/src/models/index.js, tests/integration/src/services/TaskServices.js, tests/unit/createService.test.js
=> Deprecate serviceDefaultProps function

.prettierignore
=> Prettier ignore coverage path

examples/basic/config/database.json, examples/complete/config/database.json
=> chore: Remove deprecated sequelize logger

src/Resources.js, src/routers.js, tests/unit/createService.test.js, tests/unit/routers.test.js
=> Add the resource only

README.md, bin/fastexpress.js, bin/generate.js, bin/templates-source/basic/.gitignore, bin/templates-source/basic/.sequelizerc, bin/templates-source/basic/README.md, bin/templates-source/basic/config/example.database.json, bin/templates-source/basic/package.json, bin/templates-source/basic/src/models/index.js, bin/templates-source/basic/src/routes.js, bin/templates-source/basic/src/server.js, package.json, yarn.lock
=> Add CLI with a basic template

README.md, bin/fastexpress.js, bin/newHandler.js, bin/resourceHandler.js, bin/templates/files/migration.js.handlebars, bin/templates/files/model.js.handlebars, bin/templates/files/resource.js.handlebars, bin/templates/files/seed.js.handlebars, bin/utils.js, package.json, tests/bin/utils.test.js
=> feat: Add resource command on cli and rename command generate to new

bin/resourceHandler.js, bin/templates/files/model.js.handlebars
on generate files on singular instead of plural
closes #99
=> fix: Fix the fastexpress resource command 

bin/newHandler.js, bin/templates/basic/config/example.database.json
Instead of use the template name it'll use the name of project to create a database name
=> feat: Add the name of project on database config as snakecase

src/convert.js, src/definitionsFilters.js, src/selector.js
=> refactor(selector.js): Improve the logic to make it smaller

src/Resources.js, tests/Resources.test.js
The name task was fixed on response, I added a unit test for Resources fil
=> fix(Resources.js): Add the name of resource on root tree

src/Resources.js, src/definitions.js, src/lib/getAllowedActions.js, src/routeCreator.js, src/routers.js, tests/unit/Resources.test.js, tests/unit/routeCreator.test.js, tests/unit/routers.test.js
=> feat(routeCreator.js): Add except option on routeCreator and Resource

bin/templates/basic/package.json.handlebars, examples/auth/package.json, examples/basic/package.json, examples/complete/package.json, package.json
=> build: Bump Dependencies version

bin/newHandler.js, bin/utils.js
added git init to command chain when using the "new" cli
=> added git init to command chain

.editorconfig, CONTRIBUTING.md, LICENSE, README.md
This pull request contains docs changes to make this project more new comes likely
=> docs: Add the contribuing documentation
